### ISSUE TITLE
How can I use this on Spacemacs develop branch?

### ISSUE THREAD

**Issue by ghost** [chrisbarrett/super-smart-ops#1]
First issue on this repository :P

**Comment by chrisbarrett** [comment]
Have a read through the [Spacemacs documentation on layers](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org) to learn how to implement your own layers.

You can refer to my config for code examples.
1. [Init function](https://github.com/chrisbarrett/spacemacs-layers/blob/master/cb-core/packages.el#L237)
2. [Example for OCaml](https://github.com/chrisbarrett/spacemacs-layers/blob/master/cb-ocaml/packages.el#L103)
