### ISSUE TITLE
How to imple *pointer and a * b in golang?

### ISSUE THREAD

**Issue by ghost** [chrisbarrett/super-smart-ops#3]
Hi @chrisbarrett I use your spacemacs-private and want to add a layer cb-go, the partial code looks like below:

```
(defun cb-go/post-init-smart-ops ()
  (defun cb-go/after-operator-keyword? (&rest _)
    (save-excursion
      (goto-char (smart-ops--maybe-beginning-of-op (smart-ops--rules-for-current-mode)))
      (thing-at-point-looking-at (rx bow "operator" eow (* space)))))

  (define-smart-ops-for-mode 'go-mode
    (smart-ops
     "+" "-" "/" "%" "^" "|" "!" "=" "<<" ">>" "==" "!=" "&&" "||"
     ":=" "+=" "-=" "/=" "%=" "^=" "|=" "*=" "<<=" ">>=" "?"
     :pad-unless 'cb-go/after-operator-keyword?)

    (smart-ops "," :pad-before nil :pad-unless 'cb-go/after-operator-keyword?)
    (smart-ops "&" "*"
               :pad-before-if
               (smart-ops-after-match? (rx bow "return" eow (* space) eos))
               :pad-after-unless
               (smart-ops-after-match? (rx bow "return" eow (* space) (? (or "&" "*")) eos))
               :pad-unless 'cb-go/after-operator-keyword?)

    (smart-ops "--" "++" :pad-before nil :pad-after nil)

    (smart-ops "."
               :pad-before nil :pad-after nil
               :action 'company-manual-begin)))
```

In golang, the \* with pointer looks like

```
type Chan chan *http.Request
```

So I don't know how to impl this and how to diff with a \* b, I tried (space *) but, it's not OK. Would you please give me a hand? Thank you very much!

**Comment by chrisbarrett** [comment]
I don't know Go, but I assume there isn't enough context to make that distinction. You'd probably have to write a parser to get what you want.

In your situation I'd probably just disable the after-padding, because it's more ergonomic to type a space in the situations where you need to do multiplication.

**Comment by ghost** [comment]
Thank you @chrisbarrett, I suddenly remember  "*" and "&" in go is almost the same in rust, so I solved this problem by looking your cb-rust code! :)
