### ISSUE TITLE
How is it related to smart-ops?

### ISSUE THREAD

**Issue by d12frosted** [chrisbarrett/super-smart-ops#4]
I see that you are using [smart-ops](https://github.com/chrisbarrett/spacemacs-layers/tree/master/cb-core/local/smart-ops) in your Spacemacs layers. So I can't decide, which one to use. `Super-smart-ops` claims that it's better than regular `smart-ops`, but again, why do you still using older version? :)

**Comment by chrisbarrett** [comment]
Uuuuuuuh don't use this. :)

**Comment by d12frosted** [comment]
Haha. At least I have an answer about what to use 😸 Would you consider moving `smart-ops` to separate repository so it can be easily used without cloning `spacemacs-layer` repo? 😸

**Comment by chrisbarrett** [comment]
Yeah, might do that sometime. I definitely used to do that all the time, but maintaining heaps of repos for your config is really annoying. Also, other people start depending on your config and don't like things being broken ;)

**Comment by d12frosted** [comment]
Ah, I see. I understand your point. Well anyway, thanks for that package (whenever it is).
